name: Release

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  publish-npm:
    permissions: write-all
    name: 'NPM Registry'
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: '🐰 Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun .github/changeset-version.js
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}